### ISSUE TITLE
Update dependencies of Operator and Executor

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#2088]
We should make sure that dependencies of `Operator` and `Executor` as as much up to date as it is possible. 
Once we get both up-to-date we should keep it such using dependabot to avoid a big update in the future.

This will be a parent issue linking to smaller ones listed into a checklist:

### Operator Upgrade
- [x] Assessment required
- [x] Upgrade all dependencies that upgrade is straightforward (https://github.com/SeldonIO/seldon-core/issues/2098)
- [x] Upgrace k8s.io deps to `v0.17.8` at least (https://github.com/SeldonIO/seldon-core/issues/2098)
- [x] Upgrade Zap to `v1.15.0` (https://github.com/SeldonIO/seldon-core/issues/2127)
- [x] Upgrade istio.io deps (https://github.com/SeldonIO/seldon-core/issues/2126)
- [x] Upgrade knative.dev deps (https://github.com/SeldonIO/seldon-core/issues/2128)
- [ ] ~~Verify issue with `go-logr` (https://github.com/kubernetes-sigs/controller-runtime/issues/1033)~~
- [x] Update `controller-runtime` (https://github.com/SeldonIO/seldon-core/issues/2116)

### Executor Upgrade
- [x] Assessment required
- [x] Upgrade all dependencies that upgrade is straightforward  (https://github.com/SeldonIO/seldon-core/issues/2089)
- [ ] ~~Refactor logging to lift dependency on `controller-runtime` (https://github.com/SeldonIO/seldon-core/issues/2090)~~
- [x] Upgrade Zap to `v1.15.0` (https://github.com/SeldonIO/seldon-core/issues/2127)
- [x] Upgrade Operator version in Executor deps (https://github.com/SeldonIO/seldon-core/issues/2091)
- [x] Upgrade k8s.io deps (https://github.com/SeldonIO/seldon-core/issues/2134)
- [x] Remove dependency on `client-go` (https://github.com/SeldonIO/seldon-core/issues/2092)

### Both
- [x] Verify that all direct dependencies are upgraded to reasonably recent versions
- [x] Verify possible issues with dependencies marked as `incompatible`

### Dependabot Integration:
- [x] Operator
- [x] Executor

## Update
- We are note removing Executor's dependency on Operator refactoring logging to lift dependency `controller-runtime` is not crucial for this task
- Instead of fixing Operator version in Executor https://github.com/SeldonIO/seldon-core/pull/2121 will build Executor using Operator from monorepo (replace method in go.mod + symlinking operator folder)
- go-logr package is interface definition and incompatibility seems to be present in our dependencies. As this is only interface definition updating it is not a priority for this issue

### Executor upgrade assessment
![image](https://user-images.githubusercontent.com/10928117/86942975-c033af80-c13d-11ea-8eaf-f90dc71ff03d.png)

**Comment by RafalSkolasinski** [comment]
Initial assessment for Operator

![image](https://user-images.githubusercontent.com/10928117/87025964-f8d19880-c1d2-11ea-949a-4d7190ac886d.png)

**Comment by RafalSkolasinski** [comment]
More info on go-logr and controller-runtime incompatibility issues:
- https://github.com/kubernetes-sigs/controller-runtime/pull/995
- https://github.com/kubernetes-sigs/controller-runtime/pull/1011
- https://github.com/kubernetes-sigs/controller-runtime/issues/1033
- https://github.com/go-logr/logr/pull/20

**Comment by RafalSkolasinski** [comment]
`+incomaptible` comment in go.mods means incompatibility in different ways that Go uses to handle dependencies.

good read: https://stackoverflow.com/a/57372286/5420500

**Comment by RafalSkolasinski** [comment]
With 2nd level dependencies (and further) we have very limited control as this is basically set by our dependencies. 
We will need to raise issues directly in upstream projects in case there is an CVE or another important issue to upgrade.
